#pragma once
// Generated by build script, do not edit!
#define UNITY_VERSION_FULL "2018.3.1f1_bb579dc42f1d"
#define UNITY_VERSION_FULL_NICE "2018.3.1f1 (bb579dc42f1d)"
#define UNITY_VERSION_BLD 12277661
#define UNITY_VERSION_DATE 1545647626
#define UNITY_VERSION_WIN "2018.3.1.12277661"
#define UNITY_VERSION_BRANCH "2018.3/staging"
